"""post and reply foeign keys updated

Revision ID: a6c474a0bc12
Revises: 
Create Date: 2024-10-17 17:25:15.740834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c474a0bc12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_author_name_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_name'], ['username'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('posts_author_name_fkey', 'users', ['author_name'], ['username'], ondelete='CASCADE')

    # ### end Alembic commands ###
